apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance
  template:
    metadata:
      labels:
        app: attendance
    spec:
      containers:
      - name: attendance
        image: oumaima617/attendance:v1
        ports:
        - containerPort: 5000
