apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses
spec:
  replicas: 2
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
      - name: courses
        image: oumaima617/courses:v1
        ports:
        - containerPort: 5000
