apiVersion: apps/v1
kind: Deployment
metadata:
  name: students
spec:
  replicas: 2
  selector:
    matchLabels:
      app: students
  template:
    metadata:
      labels:
        app: students
    spec:
      containers:
      - name: students
        image: oumaima617/students:v1
        ports:
        - containerPort: 5000
